---
  - name: Create YUM repository (RedHat)
    yum_repository:
      name: "{{ yum_repo_name }}"
      description: "{{ yum_repo_description }}"
      baseurl: "{{ yum_repo_baseurl }}"
      gpgkey: "{{ code_repo_key }}"
      gpgcheck: yes
      enabled: yes

  - name: Install the application package (RedHat)
    package:
      name: "{{ package_name }}"
      state: present
